### ISSUE TITLE
qgraph::flow produces weird edges for an mgm network

### ISSUE THREAD

**Issue by heinonmatti** [SachaEpskamp/qgraph#13] opened 2018-05-09 16:31 UTC
Ok, so I have this mgm-estimated network:

![image](https://user-images.githubusercontent.com/16374562/39826966-6b976498-53ae-11e8-8292-2c8b93a6c881.png)

When I plot it with flow instead, I get this:
`qgraph::flow(BCT_mgm, "PA accelerometer", theme = "colorblind", vsize = 8)`

![image](https://user-images.githubusercontent.com/16374562/39827003-81444d6a-53ae-11e8-93c4-11d11e21d144.png)

For another variable, this: 
`qgraph::flow(BCT_mgm, "PA selfrep", theme = "colorblind", vsize = 8)`

![image](https://user-images.githubusercontent.com/16374562/39827013-89448386-53ae-11e8-94bf-ae9d1e559a47.png)

Any thoughts?

**Comment by heinonmatti** [comment] 2018-05-09 16:39
Here's the covariance matrix:


[covSacha.zip](https://github.com/SachaEpskamp/qgraph/files/1988678/covSacha.zip)

**Comment by kamione** [comment] 2019-03-14 13:20
Same issue happens to me. I am thinking whether it is because the edge color specific in the mgm model does not inherit to the flow function. Any idea?

**Comment by SachaEpskamp** [comment] 2019-03-14 15:36
Hi both,

Sorry for the late response. How do I read that cov matrix Matti? And do you possibly have an easier to reproduce example? It is possible indeed that this is due to the edge colors not being supplied. Perhaps try to store the results of `flow(...)` and then manually change the edge colors in the qgraph object?

Best, Sacha

**Comment by heinonmatti** [comment] 2019-03-15 12:24
Apologies for being a bit novice with this. I now tinkered a bit with what little I could simulate, and found a hopefully more reproducible way to come about those grey edges. 

If you use 5000 instead of 200 in `MASS::mvrnorm(n = 200, mu = mus, Sigma = S)`, you'll get blue/red edges instead of grey ones, even though the categorical variables have two levels and grey edges don't appear in the "normal" (non-flow) network.

```
# Make covariance matrix. 
S <- matrix(c(1.0, 0.2, 0.1, 0.35, 0.0,
             0.2, 1.0, 0.0, 0.4, 0.0,
             0.1, 0.0, 1.0, 0.0, 0.4,
             0.35, 0.4, 0.0, 1.0, 0.6,
             0.0, 0.0, 0.4, 0.6, 1.0), ncol = 5)
colnames(S) <- c("Y1", "X1", "X2", "Z1" ,"Z2")
rownames(S) <- colnames(S)

# Make mean vector
mus <- c(1, 2, 3, 4, 5); names(mus) = colnames(S)

# Generate 5347 observations
obs <- MASS::mvrnorm(n = 200, mu = mus, Sigma = S)

obs <- data.frame(obs)
obs$categorical <- ifelse(obs$Y1 > 2, 1, 0)
obs$categorical2 <- ifelse(obs$X1 > 2, 1, 0)

bctdf_pa_combinedAgreementBcts <- obs

mgm_pa_variable_types <- c(rep("g", 5), "c", "c")
mgm_pa_variable_levels <- c(rep("1", 5), "2", "2")

mgm_obj <- mgm::mgm(data = bctdf_pa_combinedAgreementBcts,
                    type = mgm_pa_variable_types,
                    level = mgm_pa_variable_levels,
                    lambdaSel = "CV",
                    lambdaFolds = 10,
                    pbar = FALSE, 
                    binarySign = TRUE)

# PLOT NETWORK 

BCT_mgm <- qgraph::qgraph(mgm_obj$pairwise$wadj, 
                          layout = "spring",
                          repulsion = 1, # To nudge the network from originally bad visual state
                          title = "agreement-measured BCTs and PA",
                          edge.color = ifelse(mgm_obj$pairwise$edgecolor == "darkgreen", "blue", mgm_obj$pairwise$edgecolor),
                          labels = names(bctdf_pa_combinedAgreementBcts),
                          label.cex = 0.75,
                          label.scale = FALSE,
                          label.color = c(rep("black", 9)),
                          theme = "colorblind")

qgraph::flow(BCT_mgm, from = "Y1")

```

**Comment by SachaEpskamp** [comment] 2019-03-22 15:30
Right, I see. Thanks! This may not be trivial for now, I need to open up the function and add that the edge colors are also retained properly. Will put it on the todo list!

**Comment by SachaEpskamp** [comment] 2020-09-09 14:22
This is now fixed in the devel version (sorry for the delay).

**Closed by SachaEpskamp** 2020-09-09 14:22 UTC
